---
title: "About"
output:
  html_document:
    toc: false
---
<br>

##ABSTRACT  
Genetic variation modulating risk of sporadic Parkinson’s disease (PD) has been primarily explored through genome wide association studies (GWAS). However, like many other common genetic diseases, the impacted genes remain largely unknown. Here, we used single-cell RNA-seq to characterize dopaminergic (DA) neuron populations in the mouse brain at embryonic and early postnatal timepoints. These data facilitated unbiased identification of DA neuron subpopulations through their unique transcriptional profiles, including a novel postnatal neuroblast population and substantia nigra (SN) DA neurons. We use these population-specific data to develop a scoring system to prioritize candidate genes in all 49 GWAS intervals implicated in PD risk, including known PD genes and many with extensive supporting literature. As proof of principle, we confirm that the nigrostriatal pathway is compromised in Cplx1 null mice. Ultimately, this systematic approach establishes biologically pertinent candidates and testable hypotheses for sporadic PD, informing a new era of PD genetic research.  
<br>

####CITATION  
**Hook, P.W.**, McClymont, S.A., Cannon, G.H., Law, W.D., Morton, A.J., Goff, L.A., and McCallion, A.S. (2018). Single-Cell RNA-Seq of Mouse Dopaminergic Neurons Informs Candidate Gene Selection for Sporadic Parkinson Disease. Am. J. Hum. Genet. 102, 427-446. doi: <a href="http://dx.doi.org/10.1016/j.ajhg.2018.02.001" target="_blank">http://dx.doi.org/10.1016/j.ajhg.2018.02.001</a>

If DOI links do not work yet, find the paper <a href="http://www.cell.com/ajhg/fulltext/S0002-9297(18)30046-6" target="_blank">here</a>  

***

####CONTACT
This website was designed and created by **Paul Hook**  
[Twitter](https://twitter.com/paul_hook_hugen)    
[Website](https://pwh124.github.io/)       
email: phook2 [at] jhmi.edu    

***

**Last update:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

***
