---
title: Figure S5
output:
  html_document:
    toc: FALSE
---

Figure S5 is composed of plots rendered during the running of weighted gene coexpression network analysis (WGCNA). The links below lead to sections of the [P7 WGCNA Analysis code](WGCNA-final.html).

* [Figure S5A](WGCNA-final.html#making_a_data_frame_that_can_be_filled_with_meta-data_about_the_cells_and_can_be_used_to_annotate_the_heirarchial_clustering)  
A sample dendrogram after removal of outliers with regional identity for each cell displayed below the plot

* [Figure S5B](WGCNA-final.html#in_order_to_now_perform_wgcna_on_our_data,_a_%E2%80%9Csoft_threshold%E2%80%9D_needs_to_be_calculated)  
Scale independence and mean connectivity plots that allowed us to determine the "soft threshold" setting we would need for the analysis

* [Figure S5C](WGCNA-final.html#now_that_we_have_identified_modules_in_our_data,_we_want_to_explore_the_relationships_between_those_modules_a_little_more_note_that_grey_and_turquoise_modules_were_removed_in_these_analyses_because_turquoise_contained_all_genes_that_did_not_get_slotted_in_to_a_specific_module_and_grey_had_only_4_genes_(below_our_set_module_size))  
A dendrogram of the module eigengenes identified in our analysis

***
**Last update:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`  

***
